<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        DB::beginTransaction();

        DB::unprepared('SET IDENTITY_INSERT countries ON');

        DB::table('countries')->insert([
            [
                'id' => 1,
                'name' => 'Afghanistan',
                'country_code' => 'AF',
                'currency_code' => 'AFN',
                'phone_code' => '93',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 2,
                'name' => 'Albania',
                'country_code' => 'AL',
                'currency_code' => 'ALL',
                'phone_code' => '355',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 3,
                'name' => 'Algeria',
                'country_code' => 'DZ',
                'currency_code' => 'DZD',
                'phone_code' => '213',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 4,
                'name' => 'American Samoa',
                'country_code' => 'AS',
                'currency_code' => 'USD',
                'phone_code' => '1684',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 5,
                'name' => 'Andorra',
                'country_code' => 'AD',
                'currency_code' => 'EUR',
                'phone_code' => '376',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 6,
                'name' => 'Angola',
                'country_code' => 'AO',
                'currency_code' => 'AOA',
                'phone_code' => '244',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 7,
                'name' => 'Anguilla',
                'country_code' => 'AI',
                'currency_code' => 'XCD',
                'phone_code' => '1264',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 8,
                'name' => 'Antarctica',
                'country_code' => 'AQ',
                'currency_code' => 'XCD',
                'phone_code' => '0',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 9,
                'name' => 'Antigua And Barbuda',
                'country_code' => 'AG',
                'currency_code' => 'XCD',
                'phone_code' => '1268',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 10,
                'name' => 'Argentina',
                'country_code' => 'AR',
                'currency_code' => 'ARS',
                'phone_code' => '54',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 11,
                'name' => 'Armenia',
                'country_code' => 'AM',
                'currency_code' => 'AMD',
                'phone_code' => '374',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 12,
                'name' => 'Aruba',
                'country_code' => 'AW',
                'currency_code' => 'AWG',
                'phone_code' => '297',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 13,
                'name' => 'Australia',
                'country_code' => 'AU',
                'currency_code' => 'AUD',
                'phone_code' => '61',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 14,
                'name' => 'Austria',
                'country_code' => 'AT',
                'currency_code' => 'EUR',
                'phone_code' => '43',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 15,
                'name' => 'Azerbaijan',
                'country_code' => 'AZ',
                'currency_code' => 'AZN',
                'phone_code' => '994',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 16,
                'name' => 'Bahamas The',
                'country_code' => 'BS',
                'currency_code' => 'BSD',
                'phone_code' => '1242',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 17,
                'name' => 'Bahrain',
                'country_code' => 'BH',
                'currency_code' => 'BHD',
                'phone_code' => '973',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 18,
                'name' => 'Bangladesh',
                'country_code' => 'BD',
                'currency_code' => 'BDT',
                'phone_code' => '880',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 19,
                'name' => 'Barbados',
                'country_code' => 'BB',
                'currency_code' => 'BBD',
                'phone_code' => '1246',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 20,
                'name' => 'Belarus',
                'country_code' => 'BY',
                'currency_code' => 'BYR',
                'phone_code' => '375',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 21,
                'name' => 'Belgium',
                'country_code' => 'BE',
                'currency_code' => 'EUR',
                'phone_code' => '32',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 22,
                'name' => 'Belize',
                'country_code' => 'BZ',
                'currency_code' => 'BZD',
                'phone_code' => '501',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 23,
                'name' => 'Benin',
                'country_code' => 'BJ',
                'currency_code' => 'XOF',
                'phone_code' => '229',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 24,
                'name' => 'Bermuda',
                'country_code' => 'BM',
                'currency_code' => 'BMD',
                'phone_code' => '1441',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 25,
                'name' => 'Bhutan',
                'country_code' => 'BT',
                'currency_code' => 'BTN',
                'phone_code' => '975',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 26,
                'name' => 'Bolivia',
                'country_code' => 'BO',
                'currency_code' => 'BOB',
                'phone_code' => '591',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 27,
                'name' => 'Bosnia and Herzegovina',
                'country_code' => 'BA',
                'currency_code' => 'BAM',
                'phone_code' => '387',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 28,
                'name' => 'Botswana',
                'country_code' => 'BW',
                'currency_code' => 'BWP',
                'phone_code' => '267',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 29,
                'name' => 'Bouvet Island',
                'country_code' => 'BV',
                'currency_code' => 'NOK',
                'phone_code' => '0',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 30,
                'name' => 'Brazil',
                'country_code' => 'BR',
                'currency_code' => 'BRL',
                'phone_code' => '55',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 31,
                'name' => 'British Indian Ocean Territory',
                'country_code' => 'IO',
                'currency_code' => 'USD',
                'phone_code' => '246',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 32,
                'name' => 'Brunei',
                'country_code' => 'BN',
                'currency_code' => 'BND',
                'phone_code' => '673',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 33,
                'name' => 'Bulgaria',
                'country_code' => 'BG',
                'currency_code' => 'BGN',
                'phone_code' => '359',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 34,
                'name' => 'Burkina Faso',
                'country_code' => 'BF',
                'currency_code' => 'XOF',
                'phone_code' => '226',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 35,
                'name' => 'Burundi',
                'country_code' => 'BI',
                'currency_code' => 'BIF',
                'phone_code' => '257',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 36,
                'name' => 'Cambodia',
                'country_code' => 'KH',
                'currency_code' => 'KHR',
                'phone_code' => '855',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 37,
                'name' => 'Cameroon',
                'country_code' => 'CM',
                'currency_code' => 'XAF',
                'phone_code' => '237',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 38,
                'name' => 'Canada',
                'country_code' => 'CA',
                'currency_code' => 'CAD',
                'phone_code' => '1',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 39,
                'name' => 'Cape Verde',
                'country_code' => 'CV',
                'currency_code' => 'CVE',
                'phone_code' => '238',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 40,
                'name' => 'Cayman Islands',
                'country_code' => 'KY',
                'currency_code' => 'KYD',
                'phone_code' => '1345',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 41,
                'name' => 'Central African Republic',
                'country_code' => 'CF',
                'currency_code' => 'XAF',
                'phone_code' => '236',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 42,
                'name' => 'Chad',
                'country_code' => 'TD',
                'currency_code' => 'XAF',
                'phone_code' => '235',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 43,
                'name' => 'Chile',
                'country_code' => 'CL',
                'currency_code' => 'CLP',
                'phone_code' => '56',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 44,
                'name' => 'China',
                'country_code' => 'CN',
                'currency_code' => 'CNY',
                'phone_code' => '86',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 45,
                'name' => 'Christmas Island',
                'country_code' => 'CX',
                'currency_code' => 'AUD',
                'phone_code' => '61',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 46,
                'name' => 'Cocos (Keeling) Islands',
                'country_code' => 'CC',
                'currency_code' => 'AUD',
                'phone_code' => '672',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 47,
                'name' => 'Colombia',
                'country_code' => 'CO',
                'currency_code' => 'COP',
                'phone_code' => '57',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 48,
                'name' => 'Comoros',
                'country_code' => 'KM',
                'currency_code' => 'KMF',
                'phone_code' => '269',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 49,
                'name' => 'Congo',
                'country_code' => 'CG',
                'currency_code' => 'XAF',
                'phone_code' => '242',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 50,
                'name' => 'Congo The Democratic Republic Of The',
                'country_code' => 'CD',
                'currency_code' => 'CDF',
                'phone_code' => '242',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 51,
                'name' => 'Cook Islands',
                'country_code' => 'CK',
                'currency_code' => 'NZD',
                'phone_code' => '682',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 52,
                'name' => 'Costa Rica',
                'country_code' => 'CR',
                'currency_code' => 'CRC',
                'phone_code' => '506',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 53,
                'name' => 'Cote D Ivoire (Ivory Coast)',
                'country_code' => 'CI',
                'currency_code' => NULL,
                'phone_code' => '225',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 54,
                'name' => 'Croatia (Hrvatska)',
                'country_code' => 'HR',
                'currency_code' => 'HRK',
                'phone_code' => '385',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 55,
                'name' => 'Cuba',
                'country_code' => 'CU',
                'currency_code' => 'CUP',
                'phone_code' => '53',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 56,
                'name' => 'Cyprus',
                'country_code' => 'CY',
                'currency_code' => 'EUR',
                'phone_code' => '357',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 57,
                'name' => 'Czech Republic',
                'country_code' => 'CZ',
                'currency_code' => 'CZK',
                'phone_code' => '420',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 58,
                'name' => 'Denmark',
                'country_code' => 'DK',
                'currency_code' => 'DKK',
                'phone_code' => '45',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 59,
                'name' => 'Djibouti',
                'country_code' => 'DJ',
                'currency_code' => 'DJF',
                'phone_code' => '253',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 60,
                'name' => 'Dominica',
                'country_code' => 'DM',
                'currency_code' => 'XCD',
                'phone_code' => '1767',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 61,
                'name' => 'Dominican Republic',
                'country_code' => 'DO',
                'currency_code' => 'DOP',
                'phone_code' => '1809',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 62,
                'name' => 'East Timor',
                'country_code' => 'TP',
                'currency_code' => NULL,
                'phone_code' => '670',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 63,
                'name' => 'Ecuador',
                'country_code' => 'EC',
                'currency_code' => 'ECS',
                'phone_code' => '593',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 64,
                'name' => 'Egypt',
                'country_code' => 'EG',
                'currency_code' => 'EGP',
                'phone_code' => '20',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 65,
                'name' => 'El Salvador',
                'country_code' => 'SV',
                'currency_code' => 'SVC',
                'phone_code' => '503',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 66,
                'name' => 'Equatorial Guinea',
                'country_code' => 'GQ',
                'currency_code' => 'XAF',
                'phone_code' => '240',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 67,
                'name' => 'Eritrea',
                'country_code' => 'ER',
                'currency_code' => 'ERN',
                'phone_code' => '291',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 68,
                'name' => 'Estonia',
                'country_code' => 'EE',
                'currency_code' => 'EUR',
                'phone_code' => '372',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 69,
                'name' => 'Ethiopia',
                'country_code' => 'ET',
                'currency_code' => 'ETB',
                'phone_code' => '251',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 70,
                'name' => 'External Territories of Australia',
                'country_code' => 'XA',
                'currency_code' => NULL,
                'phone_code' => '61',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 71,
                'name' => 'Falkland Islands',
                'country_code' => 'FK',
                'currency_code' => 'FKP',
                'phone_code' => '500',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 72,
                'name' => 'Faroe Islands',
                'country_code' => 'FO',
                'currency_code' => 'DKK',
                'phone_code' => '298',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 73,
                'name' => 'Fiji Islands',
                'country_code' => 'FJ',
                'currency_code' => 'FJD',
                'phone_code' => '679',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 74,
                'name' => 'Finland',
                'country_code' => 'FI',
                'currency_code' => 'EUR',
                'phone_code' => '358',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 75,
                'name' => 'France',
                'country_code' => 'FR',
                'currency_code' => 'EUR',
                'phone_code' => '33',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 76,
                'name' => 'French Guiana',
                'country_code' => 'GF',
                'currency_code' => 'EUR',
                'phone_code' => '594',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 77,
                'name' => 'French Polynesia',
                'country_code' => 'PF',
                'currency_code' => NULL,
                'phone_code' => '689',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 78,
                'name' => 'French Southern Territories',
                'country_code' => 'TF',
                'currency_code' => 'EUR',
                'phone_code' => '0',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 79,
                'name' => 'Gabon',
                'country_code' => 'GA',
                'currency_code' => 'XAF',
                'phone_code' => '241',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 80,
                'name' => 'Gambia The',
                'country_code' => 'GM',
                'currency_code' => 'GMD',
                'phone_code' => '220',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 81,
                'name' => 'Georgia',
                'country_code' => 'GE',
                'currency_code' => 'GEL',
                'phone_code' => '995',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 82,
                'name' => 'Germany',
                'country_code' => 'DE',
                'currency_code' => 'EUR',
                'phone_code' => '49',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 83,
                'name' => 'Ghana',
                'country_code' => 'GH',
                'currency_code' => 'GHS',
                'phone_code' => '233',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 84,
                'name' => 'Gibraltar',
                'country_code' => 'GI',
                'currency_code' => 'GIP',
                'phone_code' => '350',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 85,
                'name' => 'Greece',
                'country_code' => 'GR',
                'currency_code' => 'EUR',
                'phone_code' => '30',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 86,
                'name' => 'Greenland',
                'country_code' => 'GL',
                'currency_code' => 'DKK',
                'phone_code' => '299',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 87,
                'name' => 'Grenada',
                'country_code' => 'GD',
                'currency_code' => 'XCD',
                'phone_code' => '1473',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 88,
                'name' => 'Guadeloupe',
                'country_code' => 'GP',
                'currency_code' => 'EUR',
                'phone_code' => '590',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 89,
                'name' => 'Guam',
                'country_code' => 'GU',
                'currency_code' => 'USD',
                'phone_code' => '1671',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 90,
                'name' => 'Guatemala',
                'country_code' => 'GT',
                'currency_code' => 'QTQ',
                'phone_code' => '502',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 91,
                'name' => 'Guernsey and Alderney',
                'country_code' => 'XU',
                'currency_code' => NULL,
                'phone_code' => '44',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 92,
                'name' => 'Guinea',
                'country_code' => 'GN',
                'currency_code' => 'GNF',
                'phone_code' => '224',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 93,
                'name' => 'Guinea-Bissau',
                'country_code' => 'GW',
                'currency_code' => 'GWP',
                'phone_code' => '245',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 94,
                'name' => 'Guyana',
                'country_code' => 'GY',
                'currency_code' => 'GYD',
                'phone_code' => '592',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 95,
                'name' => 'Haiti',
                'country_code' => 'HT',
                'currency_code' => 'HTG',
                'phone_code' => '509',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 96,
                'name' => 'Heard and McDonald Islands',
                'country_code' => 'HM',
                'currency_code' => 'AUD',
                'phone_code' => '0',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 97,
                'name' => 'Honduras',
                'country_code' => 'HN',
                'currency_code' => 'HNL',
                'phone_code' => '504',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 98,
                'name' => 'Hong Kong S.A.R.',
                'country_code' => 'HK',
                'currency_code' => 'HKD',
                'phone_code' => '852',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 99,
                'name' => 'Hungary',
                'country_code' => 'HU',
                'currency_code' => 'HUF',
                'phone_code' => '36',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 100,
                'name' => 'Iceland',
                'country_code' => 'IS',
                'currency_code' => 'ISK',
                'phone_code' => '354',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ]
        ]);

        \DB::table('countries')->insert([
            [
                'id' => 101,
                'name' => 'India',
                'country_code' => 'IN',
                'currency_code' => 'INR',
                'phone_code' => '91',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 102,
                'name' => 'Indonesia',
                'country_code' => 'ID',
                'currency_code' => 'IDR',
                'phone_code' => '62',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 103,
                'name' => 'Iran',
                'country_code' => 'IR',
                'currency_code' => 'IRR',
                'phone_code' => '98',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 104,
                'name' => 'Iraq',
                'country_code' => 'IQ',
                'currency_code' => 'IQD',
                'phone_code' => '964',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 105,
                'name' => 'Ireland',
                'country_code' => 'IE',
                'currency_code' => 'EUR',
                'phone_code' => '353',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 106,
                'name' => 'Israel',
                'country_code' => 'IL',
                'currency_code' => 'ILS',
                'phone_code' => '972',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 107,
                'name' => 'Italy',
                'country_code' => 'IT',
                'currency_code' => 'EUR',
                'phone_code' => '39',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 108,
                'name' => 'Jamaica',
                'country_code' => 'JM',
                'currency_code' => 'JMD',
                'phone_code' => '1876',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 109,
                'name' => 'Japan',
                'country_code' => 'JP',
                'currency_code' => 'JPY',
                'phone_code' => '81',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 110,
                'name' => 'Jersey',
                'country_code' => 'XJ',
                'currency_code' => NULL,
                'phone_code' => '44',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 111,
                'name' => 'Jordan',
                'country_code' => 'JO',
                'currency_code' => 'JOD',
                'phone_code' => '962',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 112,
                'name' => 'Kazakhstan',
                'country_code' => 'KZ',
                'currency_code' => 'KZT',
                'phone_code' => '7',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 113,
                'name' => 'Kenya',
                'country_code' => 'KE',
                'currency_code' => 'KES',
                'phone_code' => '254',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 114,
                'name' => 'Kiribati',
                'country_code' => 'KI',
                'currency_code' => 'AUD',
                'phone_code' => '686',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 115,
                'name' => 'Korea North',
                'country_code' => 'KP',
                'currency_code' => 'KPW',
                'phone_code' => '850',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 116,
                'name' => 'Korea South',
                'country_code' => 'KR',
                'currency_code' => 'KRW',
                'phone_code' => '82',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 117,
                'name' => 'Kuwait',
                'country_code' => 'KW',
                'currency_code' => 'KWD',
                'phone_code' => '965',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 118,
                'name' => 'Kyrgyzstan',
                'country_code' => 'KG',
                'currency_code' => 'KGS',
                'phone_code' => '996',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 119,
                'name' => 'Laos',
                'country_code' => 'LA',
                'currency_code' => 'LAK',
                'phone_code' => '856',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 120,
                'name' => 'Latvia',
                'country_code' => 'LV',
                'currency_code' => 'EUR',
                'phone_code' => '371',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 121,
                'name' => 'Lebanon',
                'country_code' => 'LB',
                'currency_code' => 'LBP',
                'phone_code' => '961',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 122,
                'name' => 'Lesotho',
                'country_code' => 'LS',
                'currency_code' => 'LSL',
                'phone_code' => '266',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 123,
                'name' => 'Liberia',
                'country_code' => 'LR',
                'currency_code' => 'LRD',
                'phone_code' => '231',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 124,
                'name' => 'Libya',
                'country_code' => 'LY',
                'currency_code' => 'LYD',
                'phone_code' => '218',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 125,
                'name' => 'Liechtenstein',
                'country_code' => 'LI',
                'currency_code' => 'CHF',
                'phone_code' => '423',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 126,
                'name' => 'Lithuania',
                'country_code' => 'LT',
                'currency_code' => 'EUR',
                'phone_code' => '370',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 127,
                'name' => 'Luxembourg',
                'country_code' => 'LU',
                'currency_code' => 'EUR',
                'phone_code' => '352',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 128,
                'name' => 'Macau S.A.R.',
                'country_code' => 'MO',
                'currency_code' => NULL,
                'phone_code' => '853',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 129,
                'name' => 'Macedonia',
                'country_code' => 'MK',
                'currency_code' => 'MKD',
                'phone_code' => '389',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 130,
                'name' => 'Madagascar',
                'country_code' => 'MG',
                'currency_code' => 'MGF',
                'phone_code' => '261',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 131,
                'name' => 'Malawi',
                'country_code' => 'MW',
                'currency_code' => 'MWK',
                'phone_code' => '265',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 132,
                'name' => 'Malaysia',
                'country_code' => 'MY',
                'currency_code' => 'MYR',
                'phone_code' => '60',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 133,
                'name' => 'Maldives',
                'country_code' => 'MV',
                'currency_code' => 'MVR',
                'phone_code' => '960',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 134,
                'name' => 'Mali',
                'country_code' => 'ML',
                'currency_code' => 'XOF',
                'phone_code' => '223',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 135,
                'name' => 'Malta',
                'country_code' => 'MT',
                'currency_code' => 'EUR',
                'phone_code' => '356',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 136,
                'name' => 'Man (Isle of)',
                'country_code' => 'XM',
                'currency_code' => NULL,
                'phone_code' => '44',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 137,
                'name' => 'Marshall Islands',
                'country_code' => 'MH',
                'currency_code' => 'USD',
                'phone_code' => '692',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 138,
                'name' => 'Martinique',
                'country_code' => 'MQ',
                'currency_code' => 'EUR',
                'phone_code' => '596',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 139,
                'name' => 'Mauritania',
                'country_code' => 'MR',
                'currency_code' => 'MRO',
                'phone_code' => '222',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 140,
                'name' => 'Mauritius',
                'country_code' => 'MU',
                'currency_code' => 'MUR',
                'phone_code' => '230',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 141,
                'name' => 'Mayotte',
                'country_code' => 'YT',
                'currency_code' => 'EUR',
                'phone_code' => '269',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 142,
                'name' => 'Mexico',
                'country_code' => 'MX',
                'currency_code' => 'MXN',
                'phone_code' => '52',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 143,
                'name' => 'Micronesia',
                'country_code' => 'FM',
                'currency_code' => 'USD',
                'phone_code' => '691',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 144,
                'name' => 'Moldova',
                'country_code' => 'MD',
                'currency_code' => 'MDL',
                'phone_code' => '373',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 145,
                'name' => 'Monaco',
                'country_code' => 'MC',
                'currency_code' => 'EUR',
                'phone_code' => '377',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 146,
                'name' => 'Mongolia',
                'country_code' => 'MN',
                'currency_code' => 'MNT',
                'phone_code' => '976',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 147,
                'name' => 'Montserrat',
                'country_code' => 'MS',
                'currency_code' => 'XCD',
                'phone_code' => '1664',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 148,
                'name' => 'Morocco',
                'country_code' => 'MA',
                'currency_code' => 'MAD',
                'phone_code' => '212',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 149,
                'name' => 'Mozambique',
                'country_code' => 'MZ',
                'currency_code' => 'MZN',
                'phone_code' => '258',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 150,
                'name' => 'Myanmar',
                'country_code' => 'MM',
                'currency_code' => 'MMK',
                'phone_code' => '95',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 151,
                'name' => 'Namibia',
                'country_code' => 'NA',
                'currency_code' => 'NAD',
                'phone_code' => '264',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 152,
                'name' => 'Nauru',
                'country_code' => 'NR',
                'currency_code' => 'AUD',
                'phone_code' => '674',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 153,
                'name' => 'Nepal',
                'country_code' => 'NP',
                'currency_code' => 'NPR',
                'phone_code' => '977',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 154,
                'name' => 'Netherlands Antilles',
                'country_code' => 'AN',
                'currency_code' => 'ANG',
                'phone_code' => '599',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 155,
                'name' => 'Netherlands The',
                'country_code' => 'NL',
                'currency_code' => 'EUR',
                'phone_code' => '31',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 156,
                'name' => 'New Caledonia',
                'country_code' => 'NC',
                'currency_code' => 'XPF',
                'phone_code' => '687',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 157,
                'name' => 'New Zealand',
                'country_code' => 'NZ',
                'currency_code' => 'NZD',
                'phone_code' => '64',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 158,
                'name' => 'Nicaragua',
                'country_code' => 'NI',
                'currency_code' => 'NIO',
                'phone_code' => '505',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 159,
                'name' => 'Niger',
                'country_code' => 'NE',
                'currency_code' => 'XOF',
                'phone_code' => '227',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 160,
                'name' => 'Nigeria',
                'country_code' => 'NG',
                'currency_code' => 'NGN',
                'phone_code' => '234',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 161,
                'name' => 'Niue',
                'country_code' => 'NU',
                'currency_code' => 'NZD',
                'phone_code' => '683',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 162,
                'name' => 'Norfolk Island',
                'country_code' => 'NF',
                'currency_code' => 'AUD',
                'phone_code' => '672',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 163,
                'name' => 'Northern Mariana Islands',
                'country_code' => 'MP',
                'currency_code' => 'USD',
                'phone_code' => '1670',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 164,
                'name' => 'Norway',
                'country_code' => 'NO',
                'currency_code' => 'NOK',
                'phone_code' => '47',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 165,
                'name' => 'Oman',
                'country_code' => 'OM',
                'currency_code' => 'OMR',
                'phone_code' => '968',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 166,
                'name' => 'Pakistan',
                'country_code' => 'PK',
                'currency_code' => 'PKR',
                'phone_code' => '92',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 167,
                'name' => 'Palau',
                'country_code' => 'PW',
                'currency_code' => 'USD',
                'phone_code' => '680',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 168,
                'name' => 'Palestinian Territory Occupied',
                'country_code' => 'PS',
                'currency_code' => NULL,
                'phone_code' => '970',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 169,
                'name' => 'Panama',
                'country_code' => 'PA',
                'currency_code' => 'PAB',
                'phone_code' => '507',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 170,
                'name' => 'Papua new Guinea',
                'country_code' => 'PG',
                'currency_code' => 'PGK',
                'phone_code' => '675',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 171,
                'name' => 'Paraguay',
                'country_code' => 'PY',
                'currency_code' => 'PYG',
                'phone_code' => '595',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 172,
                'name' => 'Peru',
                'country_code' => 'PE',
                'currency_code' => 'PEN',
                'phone_code' => '51',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 173,
                'name' => 'Philippines',
                'country_code' => 'PH',
                'currency_code' => 'PHP',
                'phone_code' => '63',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 174,
                'name' => 'Pitcairn Island',
                'country_code' => 'PN',
                'currency_code' => 'NZD',
                'phone_code' => '0',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 175,
                'name' => 'Poland',
                'country_code' => 'PL',
                'currency_code' => 'PLN',
                'phone_code' => '48',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 176,
                'name' => 'Portugal',
                'country_code' => 'PT',
                'currency_code' => 'EUR',
                'phone_code' => '351',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 177,
                'name' => 'Puerto Rico',
                'country_code' => 'PR',
                'currency_code' => 'USD',
                'phone_code' => '1787',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 178,
                'name' => 'Qatar',
                'country_code' => 'QA',
                'currency_code' => 'QAR',
                'phone_code' => '974',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 179,
                'name' => 'Reunion',
                'country_code' => 'RE',
                'currency_code' => 'EUR',
                'phone_code' => '262',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 180,
                'name' => 'Romania',
                'country_code' => 'RO',
                'currency_code' => 'RON',
                'phone_code' => '40',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 181,
                'name' => 'Russia',
                'country_code' => 'RU',
                'currency_code' => 'RUB',
                'phone_code' => '70',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 182,
                'name' => 'Rwanda',
                'country_code' => 'RW',
                'currency_code' => 'RWF',
                'phone_code' => '250',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 183,
                'name' => 'Saint Helena',
                'country_code' => 'SH',
                'currency_code' => 'SHP',
                'phone_code' => '290',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 184,
                'name' => 'Saint Kitts And Nevis',
                'country_code' => 'KN',
                'currency_code' => 'XCD',
                'phone_code' => '1869',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 185,
                'name' => 'Saint Lucia',
                'country_code' => 'LC',
                'currency_code' => 'XCD',
                'phone_code' => '1758',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 186,
                'name' => 'Saint Pierre and Miquelon',
                'country_code' => 'PM',
                'currency_code' => 'EUR',
                'phone_code' => '508',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 187,
                'name' => 'Saint Vincent And The Grenadines',
                'country_code' => 'VC',
                'currency_code' => 'XCD',
                'phone_code' => '1784',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 188,
                'name' => 'Samoa',
                'country_code' => 'WS',
                'currency_code' => 'WST',
                'phone_code' => '684',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 189,
                'name' => 'San Marino',
                'country_code' => 'SM',
                'currency_code' => 'EUR',
                'phone_code' => '378',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 190,
                'name' => 'Sao Tome and Principe',
                'country_code' => 'ST',
                'currency_code' => 'STD',
                'phone_code' => '239',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 191,
                'name' => 'Saudi Arabia',
                'country_code' => 'SA',
                'currency_code' => 'SAR',
                'phone_code' => '966',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 192,
                'name' => 'Senegal',
                'country_code' => 'SN',
                'currency_code' => 'XOF',
                'phone_code' => '221',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 193,
                'name' => 'Serbia',
                'country_code' => 'RS',
                'currency_code' => 'RSD',
                'phone_code' => '381',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 194,
                'name' => 'Seychelles',
                'country_code' => 'SC',
                'currency_code' => 'SCR',
                'phone_code' => '248',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 195,
                'name' => 'Sierra Leone',
                'country_code' => 'SL',
                'currency_code' => 'SLL',
                'phone_code' => '232',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 196,
                'name' => 'Singapore',
                'country_code' => 'SG',
                'currency_code' => 'SGD',
                'phone_code' => '65',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 197,
                'name' => 'Slovakia',
                'country_code' => 'SK',
                'currency_code' => 'EUR',
                'phone_code' => '421',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 198,
                'name' => 'Slovenia',
                'country_code' => 'SI',
                'currency_code' => 'EUR',
                'phone_code' => '386',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 199,
                'name' => 'Smaller Territories of the UK',
                'country_code' => 'XG',
                'currency_code' => NULL,
                'phone_code' => '44',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 200,
                'name' => 'Solomon Islands',
                'country_code' => 'SB',
                'currency_code' => 'SBD',
                'phone_code' => '677',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ]
        ]);
        \DB::table('countries')->insert([
            [
                'id' => 201,
                'name' => 'Somalia',
                'country_code' => 'SO',
                'currency_code' => 'SOS',
                'phone_code' => '252',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 202,
                'name' => 'South Africa',
                'country_code' => 'ZA',
                'currency_code' => 'ZAR',
                'phone_code' => '27',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 203,
                'name' => 'South Georgia',
                'country_code' => 'GS',
                'currency_code' => 'GBP',
                'phone_code' => '0',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 204,
                'name' => 'South Sudan',
                'country_code' => 'SS',
                'currency_code' => 'SSP',
                'phone_code' => '211',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 205,
                'name' => 'Spain',
                'country_code' => 'ES',
                'currency_code' => 'EUR',
                'phone_code' => '34',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 206,
                'name' => 'Sri Lanka',
                'country_code' => 'LK',
                'currency_code' => 'LKR',
                'phone_code' => '94',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 207,
                'name' => 'Sudan',
                'country_code' => 'SD',
                'currency_code' => 'SDG',
                'phone_code' => '249',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 208,
                'name' => 'Suriname',
                'country_code' => 'SR',
                'currency_code' => 'SRD',
                'phone_code' => '597',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 209,
                'name' => 'Svalbard And Jan Mayen Islands',
                'country_code' => 'SJ',
                'currency_code' => 'NOK',
                'phone_code' => '47',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 210,
                'name' => 'Swaziland',
                'country_code' => 'SZ',
                'currency_code' => 'SZL',
                'phone_code' => '268',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 211,
                'name' => 'Sweden',
                'country_code' => 'SE',
                'currency_code' => 'SEK',
                'phone_code' => '46',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 212,
                'name' => 'Switzerland',
                'country_code' => 'CH',
                'currency_code' => 'CHF',
                'phone_code' => '41',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 213,
                'name' => 'Syria',
                'country_code' => 'SY',
                'currency_code' => 'SYP',
                'phone_code' => '963',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 214,
                'name' => 'Taiwan',
                'country_code' => 'TW',
                'currency_code' => 'TWD',
                'phone_code' => '886',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 215,
                'name' => 'Tajikistan',
                'country_code' => 'TJ',
                'currency_code' => 'TJS',
                'phone_code' => '992',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 216,
                'name' => 'Tanzania',
                'country_code' => 'TZ',
                'currency_code' => 'TZS',
                'phone_code' => '255',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 217,
                'name' => 'Thailand',
                'country_code' => 'TH',
                'currency_code' => 'THB',
                'phone_code' => '66',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 218,
                'name' => 'Togo',
                'country_code' => 'TG',
                'currency_code' => 'XOF',
                'phone_code' => '228',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 219,
                'name' => 'Tokelau',
                'country_code' => 'TK',
                'currency_code' => 'NZD',
                'phone_code' => '690',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 220,
                'name' => 'Tonga',
                'country_code' => 'TO',
                'currency_code' => 'TOP',
                'phone_code' => '676',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 221,
                'name' => 'Trinidad And Tobago',
                'country_code' => 'TT',
                'currency_code' => 'TTD',
                'phone_code' => '1868',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 222,
                'name' => 'Tunisia',
                'country_code' => 'TN',
                'currency_code' => 'TND',
                'phone_code' => '216',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 223,
                'name' => 'Turkey',
                'country_code' => 'TR',
                'currency_code' => 'TRY',
                'phone_code' => '90',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 224,
                'name' => 'Turkmenistan',
                'country_code' => 'TM',
                'currency_code' => 'TMT',
                'phone_code' => '7370',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 225,
                'name' => 'Turks And Caicos Islands',
                'country_code' => 'TC',
                'currency_code' => 'USD',
                'phone_code' => '1649',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 226,
                'name' => 'Tuvalu',
                'country_code' => 'TV',
                'currency_code' => 'AUD',
                'phone_code' => '688',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 227,
                'name' => 'Uganda',
                'country_code' => 'UG',
                'currency_code' => 'UGX',
                'phone_code' => '256',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 228,
                'name' => 'Ukraine',
                'country_code' => 'UA',
                'currency_code' => 'UAH',
                'phone_code' => '380',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 229,
                'name' => 'United Arab Emirates',
                'country_code' => 'AE',
                'currency_code' => 'AED',
                'phone_code' => '971',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 230,
                'name' => 'United Kingdom',
                'country_code' => 'GB',
                'currency_code' => 'GBP',
                'phone_code' => '44',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 231,
                'name' => 'United States',
                'country_code' => 'US',
                'currency_code' => 'USD',
                'phone_code' => '1',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 232,
                'name' => 'United States Minor Outlying Islands',
                'country_code' => 'UM',
                'currency_code' => 'USD',
                'phone_code' => '1',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 233,
                'name' => 'Uruguay',
                'country_code' => 'UY',
                'currency_code' => 'UYU',
                'phone_code' => '598',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 234,
                'name' => 'Uzbekistan',
                'country_code' => 'UZ',
                'currency_code' => 'UZS',
                'phone_code' => '998',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 235,
                'name' => 'Vanuatu',
                'country_code' => 'VU',
                'currency_code' => 'VUV',
                'phone_code' => '678',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 236,
                'name' => 'Vatican City State (Holy See)',
                'country_code' => 'VA',
                'currency_code' => NULL,
                'phone_code' => '39',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 237,
                'name' => 'Venezuela',
                'country_code' => 'VE',
                'currency_code' => 'VEF',
                'phone_code' => '58',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 238,
                'name' => 'Vietnam',
                'country_code' => 'VN',
                'currency_code' => 'VND',
                'phone_code' => '84',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 239,
                'name' => 'Virgin Islands (British)',
                'country_code' => 'VG',
                'currency_code' => NULL,
                'phone_code' => '1284',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 240,
                'name' => 'Virgin Islands (US)',
                'country_code' => 'VI',
                'currency_code' => 'USD',
                'phone_code' => '1340',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 241,
                'name' => 'Wallis And Futuna Islands',
                'country_code' => 'WF',
                'currency_code' => 'XPF',
                'phone_code' => '681',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 242,
                'name' => 'Western Sahara',
                'country_code' => 'EH',
                'currency_code' => 'MAD',
                'phone_code' => '212',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 243,
                'name' => 'Yemen',
                'country_code' => 'YE',
                'currency_code' => 'YER',
                'phone_code' => '967',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 244,
                'name' => 'Yugoslavia',
                'country_code' => 'YU',
                'currency_code' => NULL,
                'phone_code' => '38',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 245,
                'name' => 'Zambia',
                'country_code' => 'ZM',
                'currency_code' => 'ZMW',
                'phone_code' => '260',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
            [
                'id' => 246,
                'name' => 'Zimbabwe',
                'country_code' => 'ZW',
                'currency_code' => 'ZWD',
                'phone_code' => '263',
                'currency' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-12-26 14:32:13',
            ],
        ]);

        DB::unprepared('SET IDENTITY_INSERT countries OFF');

        DB::commit();
    }
}
