<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencyTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        DB::table('currencies')->delete();

        DB::beginTransaction();

        DB::unprepared('SET IDENTITY_INSERT currencies ON');

        DB::table('currencies')->insert([
            [
                'id' => 1,
                'name' => 'Afghan Afghani',
                'code' => 'AFN',
                'symbol' => '؋',
                'country_code' => 'AF',
                'exchange_rate' => '1.0694',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:13',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 2,
                'name' => 'Albanian Lek',
                'code' => 'ALL',
                'symbol' => 'L',
                'country_code' => 'AL',
                'exchange_rate' => '1.2975',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:14',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 3,
                'name' => 'Algerian Dinar',
                'code' => 'DZD',
                'symbol' => 'دج',
                'country_code' => 'DZ',
                'exchange_rate' => '1.6623',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:14',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 4,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'AS',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:14',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 5,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'AD',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:14',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 6,
                'name' => 'Angolan Kwanza',
                'code' => 'AOA',
                'symbol' => 'Kz',
                'country_code' => 'AO',
                'exchange_rate' => '6.0905',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:14',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 7,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'AI',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:14',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 8,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'AQ',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:15',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 9,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'AG',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:15',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 10,
                'name' => 'Argentine Peso',
                'code' => 'ARS',
                'symbol' => '$',
                'country_code' => 'AR',
                'exchange_rate' => '2.1064',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:15',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 11,
                'name' => 'Armenian Dram',
                'code' => 'AMD',
                'symbol' => '֏',
                'country_code' => 'AM',
                'exchange_rate' => '4.7684',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:15',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 12,
                'name' => 'Aruban Florin',
                'code' => 'AWG',
                'symbol' => 'ƒ',
                'country_code' => 'AW',
                'exchange_rate' => '0.0218',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:15',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 13,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'AU',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:15',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 14,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'AT',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:16',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 15,
                'name' => 'Azerbaijani Manat',
                'code' => 'AZN',
                'symbol' => '₼',
                'country_code' => 'AZ',
                'exchange_rate' => '0.0205',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:16',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 16,
                'name' => 'Bahamian Dollar',
                'code' => 'BSD',
                'symbol' => '$',
                'country_code' => 'BS',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:16',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 17,
                'name' => 'Bahraini Dinar',
                'code' => 'BHD',
                'symbol' => '.د.ب',
                'country_code' => 'BH',
                'exchange_rate' => '0.0046',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:16',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 18,
                'name' => 'Bangladeshi Taka',
                'code' => 'BDT',
                'symbol' => '৳',
                'country_code' => 'BD',
                'exchange_rate' => '1.2791',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:16',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 19,
                'name' => 'Barbadian Dollar',
                'code' => 'BBD',
                'symbol' => '$',
                'country_code' => 'BB',
                'exchange_rate' => '0.0244',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:16',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 20,
                'name' => 'Belarusian Ruble',
                'code' => 'BYR',
                'symbol' => 'Br',
                'country_code' => 'BY',
                'exchange_rate' => '236.9138',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:17',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 21,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'BE',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:17',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 22,
                'name' => 'Belize Dollar',
                'code' => 'BZD',
                'symbol' => 'BZ$',
                'country_code' => 'BZ',
                'exchange_rate' => '0.0244',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:17',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 23,
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'symbol' => 'CFA',
                'country_code' => 'BJ',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:17',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 24,
                'name' => 'Bermudan Dollar',
                'code' => 'BMD',
                'symbol' => '$',
                'country_code' => 'BM',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:17',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 25,
                'name' => 'Bhutanese Ngultrum',
                'code' => 'BTN',
                'symbol' => 'Nu.',
                'country_code' => 'BT',
                'exchange_rate' => '1.0008',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:18',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 26,
                'name' => 'Bolivian Boliviano',
                'code' => 'BOB',
                'symbol' => '$b',
                'country_code' => 'BO',
                'exchange_rate' => '0.0835',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:18',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 27,
                'name' => 'Bosnia-Herzegovina Convertible Mark',
                'code' => 'BAM',
                'symbol' => 'KM',
                'country_code' => 'BA',
                'exchange_rate' => '0.0223',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:18',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 28,
                'name' => 'Botswanan Pula',
                'code' => 'BWP',
                'symbol' => 'P',
                'country_code' => 'BW',
                'exchange_rate' => '0.1549',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:18',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 29,
                'name' => 'Norwegian Krone',
                'code' => 'NOK',
                'symbol' => 'kr',
                'country_code' => 'BV',
                'exchange_rate' => '0.1191',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:19',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 30,
                'name' => 'Brazilian Real',
                'code' => 'BRL',
                'symbol' => 'R$',
                'country_code' => 'BR',
                'exchange_rate' => '0.0628',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:19',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 31,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'IO',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:19',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 32,
                'name' => 'Brunei Dollar',
                'code' => 'BND',
                'symbol' => '$',
                'country_code' => 'BN',
                'exchange_rate' => '0.0163',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:19',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 33,
                'name' => 'Bulgarian Lev',
                'code' => 'BGN',
                'symbol' => 'лв',
                'country_code' => 'BG',
                'exchange_rate' => '0.0223',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:19',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 34,
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'symbol' => 'CFA',
                'country_code' => 'BF',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:19',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 35,
                'name' => 'Burundian Franc',
                'code' => 'BIF',
                'symbol' => 'FBu',
                'country_code' => 'BI',
                'exchange_rate' => '25.0422',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:20',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 36,
                'name' => 'Cambodian Riel',
                'code' => 'KHR',
                'symbol' => '៛',
                'country_code' => 'KH',
                'exchange_rate' => '49.7125',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:20',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 37,
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'country_code' => 'CM',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:20',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 38,
                'name' => 'Canadian Dollar',
                'code' => 'CAD',
                'symbol' => '$',
                'country_code' => 'CA',
                'exchange_rate' => '0.0164',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:20',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 39,
                'name' => 'Cape Verdean Escudo',
                'code' => 'CVE',
                'symbol' => '$',
                'country_code' => 'CV',
                'exchange_rate' => '1.2554',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:21',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 40,
                'name' => 'Cayman Islands Dollar',
                'code' => 'KYD',
                'symbol' => '$',
                'country_code' => 'KY',
                'exchange_rate' => '0.0101',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:21',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 41,
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'country_code' => 'CF',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:21',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 42,
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'country_code' => 'TD',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:22',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 43,
                'name' => 'Chilean Peso',
                'code' => 'CLP',
                'symbol' => '$',
                'country_code' => 'CL',
                'exchange_rate' => '10.6279',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:22',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 44,
                'name' => 'Chinese Yuan',
                'code' => 'CNY',
                'symbol' => '¥',
                'country_code' => 'CN',
                'exchange_rate' => '0.0842',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:22',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 45,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'CX',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:22',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 46,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'CC',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:23',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 47,
                'name' => 'Colombian Peso',
                'code' => 'COP',
                'symbol' => '$',
                'country_code' => 'CO',
                'exchange_rate' => '57.5241',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:23',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 48,
                'name' => 'Comorian Franc',
                'code' => 'KMF',
                'symbol' => 'CF',
                'country_code' => 'KM',
                'exchange_rate' => '5.6092',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:23',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 49,
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'country_code' => 'CG',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:23',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 50,
                'name' => 'Congolese Franc',
                'code' => 'CDF',
                'symbol' => 'FC',
                'country_code' => 'CD',
                'exchange_rate' => '24.5979',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:23',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 51,
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => '$',
                'country_code' => 'CK',
                'exchange_rate' => '0.0193',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:24',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 52,
                'name' => 'Costa Rican Colón',
                'code' => 'CRC',
                'symbol' => '₡',
                'country_code' => 'CR',
                'exchange_rate' => '7.0331',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:24',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 53,
                'name' => 'Cote D Ivoire (Ivory Coast)',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'CI',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:24',
                'updated_at' => '2022-12-26 14:32:14',
            ],
            [
                'id' => 54,
                'name' => 'Croatian Kuna',
                'code' => 'HRK',
                'symbol' => 'kn',
                'country_code' => 'HR',
                'exchange_rate' => '0.0858',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:24',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 55,
                'name' => 'Cuban Peso',
                'code' => 'CUP',
                'symbol' => '₱',
                'country_code' => 'CU',
                'exchange_rate' => '0.3203',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:24',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 56,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'CY',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:24',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 57,
                'name' => 'Czech Republic Koruna',
                'code' => 'CZK',
                'symbol' => 'Kč',
                'country_code' => 'CZ',
                'exchange_rate' => '0.2753',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:25',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 58,
                'name' => 'Danish Krone',
                'code' => 'DKK',
                'symbol' => 'kr',
                'country_code' => 'DK',
                'exchange_rate' => '0.0846',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:25',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 59,
                'name' => 'Djiboutian Franc',
                'code' => 'DJF',
                'symbol' => 'Fdj',
                'country_code' => 'DJ',
                'exchange_rate' => '2.1507',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:25',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 60,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'DM',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:26',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 61,
                'name' => 'Dominican Peso',
                'code' => 'DOP',
                'symbol' => 'RD$',
                'country_code' => 'DO',
                'exchange_rate' => '0.6761',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:26',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 62,
                'name' => 'East Timor',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'TP',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:26',
                'updated_at' => '2022-12-26 14:32:14',
            ],
            [
                'id' => 63,
                'name' => 'Ecuador',
                'code' => 'ECS',
                'symbol' => NULL,
                'country_code' => 'EC',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:27',
                'updated_at' => '2022-12-26 14:32:14',
            ],
            [
                'id' => 64,
                'name' => 'Egyptian Pound',
                'code' => 'EGP',
                'symbol' => '£',
                'country_code' => 'EG',
                'exchange_rate' => '0.2989',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:27',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 65,
                'name' => 'Salvadoran Colón',
                'code' => 'SVC',
                'symbol' => '$',
                'country_code' => 'SV',
                'exchange_rate' => '0.1057',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:27',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 66,
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'country_code' => 'GQ',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:27',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 67,
                'name' => 'Eritrean Nakfa',
                'code' => 'ERN',
                'symbol' => 'Nfk',
                'country_code' => 'ER',
                'exchange_rate' => '0.1813',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:27',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 68,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'EE',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:27',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 69,
                'name' => 'Ethiopian Birr',
                'code' => 'ETB',
                'symbol' => 'Br',
                'country_code' => 'ET',
                'exchange_rate' => '0.6472',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:28',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 70,
                'name' => 'External Territories of Australia',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'XA',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:28',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 71,
                'name' => 'Falkland Islands Pound',
                'code' => 'FKP',
                'symbol' => '£',
                'country_code' => 'FK',
                'exchange_rate' => '0.0100',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:28',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 72,
                'name' => 'Danish Krone',
                'code' => 'DKK',
                'symbol' => 'kr',
                'country_code' => 'FO',
                'exchange_rate' => '0.0846',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:28',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 73,
                'name' => 'Fijian Dollar',
                'code' => 'FJD',
                'symbol' => '$',
                'country_code' => 'FJ',
                'exchange_rate' => '0.0270',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:28',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 74,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'FI',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:28',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 75,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'FR',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:29',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 76,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'GF',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:29',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 77,
                'name' => 'French Polynesia',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'PF',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:29',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 78,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'TF',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:29',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 79,
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'country_code' => 'GA',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:29',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 80,
                'name' => 'Gambian Dalasi',
                'code' => 'GMD',
                'symbol' => 'D',
                'country_code' => 'GM',
                'exchange_rate' => '0.7488',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:29',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 81,
                'name' => 'Georgian Lari',
                'code' => 'GEL',
                'symbol' => '₾',
                'country_code' => 'GE',
                'exchange_rate' => '0.0323',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:30',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 82,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'DE',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:30',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 83,
                'name' => 'Ghanaian Cedi',
                'code' => 'GHS',
                'symbol' => 'GH₵',
                'country_code' => 'GH',
                'exchange_rate' => '0.1208',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:30',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 84,
                'name' => 'Gibraltar Pound',
                'code' => 'GIP',
                'symbol' => '£',
                'country_code' => 'GI',
                'exchange_rate' => '0.0100',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:30',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 85,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'GR',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:30',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 86,
                'name' => 'Danish Krone',
                'code' => 'DKK',
                'symbol' => 'kr',
                'country_code' => 'GL',
                'exchange_rate' => '0.0846',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:30',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 87,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'GD',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:31',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 88,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'GP',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:31',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 89,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'GU',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:31',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 90,
                'name' => 'Guatemala',
                'code' => 'QTQ',
                'symbol' => NULL,
                'country_code' => 'GT',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:31',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 91,
                'name' => 'Guernsey and Alderney',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'XU',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:31',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 92,
                'name' => 'Guinean Franc',
                'code' => 'GNF',
                'symbol' => 'FG',
                'country_code' => 'GN',
                'exchange_rate' => '104.1624',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:31',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 93,
                'name' => 'Guinea-Bissau',
                'code' => 'GWP',
                'symbol' => NULL,
                'country_code' => 'GW',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:32',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 94,
                'name' => 'Guyanaese Dollar',
                'code' => 'GYD',
                'symbol' => '$',
                'country_code' => 'GY',
                'exchange_rate' => '2.5282',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:32',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 95,
                'name' => 'Haitian Gourde',
                'code' => 'HTG',
                'symbol' => 'G',
                'country_code' => 'HT',
                'exchange_rate' => '1.7763',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:32',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 96,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'HM',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:32',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 97,
                'name' => 'Honduran Lempira',
                'code' => 'HNL',
                'symbol' => 'L',
                'country_code' => 'HN',
                'exchange_rate' => '0.2982',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:32',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 98,
                'name' => 'Hong Kong Dollar',
                'code' => 'HKD',
                'symbol' => '$',
                'country_code' => 'HK',
                'exchange_rate' => '0.0944',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:32',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 99,
                'name' => 'Hungarian Forint',
                'code' => 'HUF',
                'symbol' => 'Ft',
                'country_code' => 'HU',
                'exchange_rate' => '4.5570',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:33',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 100,
                'name' => 'Icelandic Króna',
                'code' => 'ISK',
                'symbol' => 'kr',
                'country_code' => 'IS',
                'exchange_rate' => '1.7319',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:33',
                'updated_at' => '2022-12-26 14:32:18',
            ]
        ]);

        DB::table('currencies')->insert([
            [
                'id' => 101,
                'name' => 'Indian Rupee',
                'code' => 'INR',
                'symbol' => '₹',
                'country_code' => 'IN',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:33',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 102,
                'name' => 'Indonesian Rupiah',
                'code' => 'IDR',
                'symbol' => 'Rp',
                'country_code' => 'ID',
                'exchange_rate' => '188.8723',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:33',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 103,
                'name' => 'Iranian Rial',
                'code' => 'IRR',
                'symbol' => '﷼',
                'country_code' => 'IR',
                'exchange_rate' => '504.0463',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:33',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 104,
                'name' => 'Iraqi Dinar',
                'code' => 'IQD',
                'symbol' => 'ع.د',
                'country_code' => 'IQ',
                'exchange_rate' => '17.6365',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:33',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 105,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'IE',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:34',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 106,
                'name' => 'Israeli New Sheqel',
                'code' => 'ILS',
                'symbol' => '₪',
                'country_code' => 'IL',
                'exchange_rate' => '0.0423',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:34',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 107,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'IT',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:34',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 108,
                'name' => 'Jamaican Dollar',
                'code' => 'JMD',
                'symbol' => 'J$',
                'country_code' => 'JM',
                'exchange_rate' => '1.8413',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:34',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 109,
                'name' => 'Japanese Yen',
                'code' => 'JPY',
                'symbol' => '¥',
                'country_code' => 'JP',
                'exchange_rate' => '1.6074',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:34',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 110,
                'name' => 'Jersey',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'XJ',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:34',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 111,
                'name' => 'Jordanian Dinar',
                'code' => 'JOD',
                'symbol' => 'JD',
                'country_code' => 'JO',
                'exchange_rate' => '0.0086',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:35',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 112,
                'name' => 'Kazakhstani Tenge',
                'code' => 'KZT',
                'symbol' => '₸',
                'country_code' => 'KZ',
                'exchange_rate' => '5.5785',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:35',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 113,
                'name' => 'Kenyan Shilling',
                'code' => 'KES',
                'symbol' => 'KSh',
                'country_code' => 'KE',
                'exchange_rate' => '1.4893',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:35',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 114,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'KI',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:35',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 115,
                'name' => 'North Korean Won',
                'code' => 'KPW',
                'symbol' => '₩',
                'country_code' => 'KP',
                'exchange_rate' => '10.8787',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:35',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 116,
                'name' => 'South Korean Won',
                'code' => 'KRW',
                'symbol' => '₩',
                'country_code' => 'KR',
                'exchange_rate' => '15.4183',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:35',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 117,
                'name' => 'Kuwaiti Dinar',
                'code' => 'KWD',
                'symbol' => 'KD',
                'country_code' => 'KW',
                'exchange_rate' => '0.0037',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:36',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 118,
                'name' => 'Kyrgystani Som',
                'code' => 'KGS',
                'symbol' => 'лв',
                'country_code' => 'KG',
                'exchange_rate' => '1.0356',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:36',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 119,
                'name' => 'Laotian Kip',
                'code' => 'LAK',
                'symbol' => '₭',
                'country_code' => 'LA',
                'exchange_rate' => '209.2592',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:36',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 120,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'LV',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:36',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 121,
                'name' => 'Lebanese Pound',
                'code' => 'LBP',
                'symbol' => '£',
                'country_code' => 'LB',
                'exchange_rate' => '18.2663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:36',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 122,
                'name' => 'Lesotho Loti',
                'code' => 'LSL',
                'symbol' => 'M',
                'country_code' => 'LS',
                'exchange_rate' => '0.2054',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:36',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 123,
                'name' => 'Liberian Dollar',
                'code' => 'LRD',
                'symbol' => '$',
                'country_code' => 'LR',
                'exchange_rate' => '1.8669',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:36',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 124,
                'name' => 'Libyan Dinar',
                'code' => 'LYD',
                'symbol' => 'LD',
                'country_code' => 'LY',
                'exchange_rate' => '0.0582',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:37',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 125,
                'name' => 'Swiss Franc',
                'code' => 'CHF',
                'symbol' => 'CHF',
                'country_code' => 'LI',
                'exchange_rate' => '0.0113',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:37',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 126,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'LT',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:37',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 127,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'LU',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:37',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 128,
                'name' => 'Macau S.A.R.',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'MO',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:37',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 129,
                'name' => 'Macedonian Denar',
                'code' => 'MKD',
                'symbol' => 'ден',
                'country_code' => 'MK',
                'exchange_rate' => '0.7015',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:37',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 130,
                'name' => 'Madagascar',
                'code' => 'MGF',
                'symbol' => NULL,
                'country_code' => 'MG',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:38',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 131,
                'name' => 'Malawian Kwacha',
                'code' => 'MWK',
                'symbol' => 'MK',
                'country_code' => 'MW',
                'exchange_rate' => '12.4003',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:38',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 132,
                'name' => 'Malaysian Ringgit',
                'code' => 'MYR',
                'symbol' => 'RM',
                'country_code' => 'MY',
                'exchange_rate' => '0.0535',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:38',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 133,
                'name' => 'Maldivian Rufiyaa',
                'code' => 'MVR',
                'symbol' => 'Rf',
                'country_code' => 'MV',
                'exchange_rate' => '0.1861',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:38',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 134,
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'symbol' => 'CFA',
                'country_code' => 'ML',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:38',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 135,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'MT',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:39',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 136,
                'name' => 'Man (Isle of)',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'XM',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:39',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 137,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'MH',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:39',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 138,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'MQ',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:39',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 139,
                'name' => 'Mauritanian Ouguiya',
                'code' => 'MRO',
                'symbol' => 'UM',
                'country_code' => 'MR',
                'exchange_rate' => '4.3152',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:39',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 140,
                'name' => 'Mauritian Rupee',
                'code' => 'MUR',
                'symbol' => '₨',
                'country_code' => 'MU',
                'exchange_rate' => '0.5276',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:39',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 141,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'YT',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:40',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 142,
                'name' => 'Mexican Peso',
                'code' => 'MXN',
                'symbol' => '$',
                'country_code' => 'MX',
                'exchange_rate' => '0.2342',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:40',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 143,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'FM',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:40',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 144,
                'name' => 'Moldovan Leu',
                'code' => 'MDL',
                'symbol' => 'lei',
                'country_code' => 'MD',
                'exchange_rate' => '0.2325',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:40',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 145,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'MC',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:40',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 146,
                'name' => 'Mongolian Tugrik',
                'code' => 'MNT',
                'symbol' => '₮',
                'country_code' => 'MN',
                'exchange_rate' => '41.6533',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:40',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 147,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'MS',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:41',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 148,
                'name' => 'Moroccan Dirham',
                'code' => 'MAD',
                'symbol' => 'MAD',
                'country_code' => 'MA',
                'exchange_rate' => '0.1269',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:41',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 149,
                'name' => 'Mozambican Metical',
                'code' => 'MZN',
                'symbol' => 'MT',
                'country_code' => 'MZ',
                'exchange_rate' => '0.7715',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:41',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 150,
                'name' => 'Myanma Kyat',
                'code' => 'MMK',
                'symbol' => 'K',
                'country_code' => 'MM',
                'exchange_rate' => '25.3699',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:41',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 151,
                'name' => 'Namibian Dollar',
                'code' => 'NAD',
                'symbol' => '$',
                'country_code' => 'NA',
                'exchange_rate' => '0.2054',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:41',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 152,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'NR',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:41',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 153,
                'name' => 'Nepalese Rupee',
                'code' => 'NPR',
                'symbol' => '₨',
                'country_code' => 'NP',
                'exchange_rate' => '1.6013',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:42',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 154,
                'name' => 'Netherlands Antillean Guilder',
                'code' => 'ANG',
                'symbol' => 'ƒ',
                'country_code' => 'AN',
                'exchange_rate' => '0.0218',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:42',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 155,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'NL',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:42',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 156,
                'name' => 'CFP Franc',
                'code' => 'XPF',
                'symbol' => '₣',
                'country_code' => 'NC',
                'exchange_rate' => '1.3641',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:42',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 157,
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => '$',
                'country_code' => 'NZ',
                'exchange_rate' => '0.0193',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:42',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 158,
                'name' => 'Nicaraguan Córdoba',
                'code' => 'NIO',
                'symbol' => 'C$',
                'country_code' => 'NI',
                'exchange_rate' => '0.4412',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:42',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 159,
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'symbol' => 'CFA',
                'country_code' => 'NE',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:43',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 160,
                'name' => 'Nigerian Naira',
                'code' => 'NGN',
                'symbol' => '₦',
                'country_code' => 'NG',
                'exchange_rate' => '5.3986',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:43',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 161,
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => '$',
                'country_code' => 'NU',
                'exchange_rate' => '0.0193',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:43',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 162,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'NF',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:43',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 163,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'MP',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:43',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 164,
                'name' => 'Norwegian Krone',
                'code' => 'NOK',
                'symbol' => 'kr',
                'country_code' => 'NO',
                'exchange_rate' => '0.1191',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:43',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 165,
                'name' => 'Omani Rial',
                'code' => 'OMR',
                'symbol' => '﷼',
                'country_code' => 'OM',
                'exchange_rate' => '0.0047',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:44',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 166,
                'name' => 'Pakistani Rupee',
                'code' => 'PKR',
                'symbol' => '₨',
                'country_code' => 'PK',
                'exchange_rate' => '2.7348',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:44',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 167,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'PW',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:44',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 168,
                'name' => 'Palestinian Territory Occupied',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'PS',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:44',
                'updated_at' => '2022-12-26 14:32:15',
            ],
            [
                'id' => 169,
                'name' => 'Panamanian Balboa',
                'code' => 'PAB',
                'symbol' => 'B/.',
                'country_code' => 'PA',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:44',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 170,
                'name' => 'Papua New Guinean Kina',
                'code' => 'PGK',
                'symbol' => 'K',
                'country_code' => 'PG',
                'exchange_rate' => '0.0426',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:44',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 171,
                'name' => 'Paraguayan Guarani',
                'code' => 'PYG',
                'symbol' => 'Gs',
                'country_code' => 'PY',
                'exchange_rate' => '88.2891',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:45',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 172,
                'name' => 'Peruvian Nuevo Sol',
                'code' => 'PEN',
                'symbol' => 'S/.',
                'country_code' => 'PE',
                'exchange_rate' => '0.0460',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:45',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 173,
                'name' => 'Philippine Peso',
                'code' => 'PHP',
                'symbol' => '₱',
                'country_code' => 'PH',
                'exchange_rate' => '0.6658',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:45',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 174,
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => '$',
                'country_code' => 'PN',
                'exchange_rate' => '0.0193',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:45',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 175,
                'name' => 'Polish Zloty',
                'code' => 'PLN',
                'symbol' => 'zł',
                'country_code' => 'PL',
                'exchange_rate' => '0.0528',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:45',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 176,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'PT',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:45',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 177,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'PR',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:45',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 178,
                'name' => 'Qatari Rial',
                'code' => 'QAR',
                'symbol' => '﷼',
                'country_code' => 'QA',
                'exchange_rate' => '0.0440',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:46',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 179,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'RE',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:46',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 180,
                'name' => 'Romanian Leu',
                'code' => 'RON',
                'symbol' => 'lei',
                'country_code' => 'RO',
                'exchange_rate' => '0.0560',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:46',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 181,
                'name' => 'Russian Ruble',
                'code' => 'RUB',
                'symbol' => '₽',
                'country_code' => 'RU',
                'exchange_rate' => '0.8264',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:46',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 182,
                'name' => 'Rwandan Franc',
                'code' => 'RWF',
                'symbol' => 'R₣',
                'country_code' => 'RW',
                'exchange_rate' => '12.8823',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:46',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 183,
                'name' => 'Saint Helena Pound',
                'code' => 'SHP',
                'symbol' => '£',
                'country_code' => 'SH',
                'exchange_rate' => '0.0166',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:46',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 184,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'KN',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:47',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 185,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'LC',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:47',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 186,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'PM',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:47',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 187,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'symbol' => '$',
                'country_code' => 'VC',
                'exchange_rate' => '0.0327',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:47',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 188,
                'name' => 'Samoan Tala',
                'code' => 'WST',
                'symbol' => 'WS$',
                'country_code' => 'WS',
                'exchange_rate' => '0.0329',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:47',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 189,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'SM',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:47',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 190,
                'name' => 'São Tomé and Príncipe Dobra',
                'code' => 'STD',
                'symbol' => 'Db',
                'country_code' => 'ST',
                'exchange_rate' => '250.1856',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:48',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 191,
                'name' => 'Saudi Riyal',
                'code' => 'SAR',
                'symbol' => '﷼',
                'country_code' => 'SA',
                'exchange_rate' => '0.0455',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:48',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 192,
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'symbol' => 'CFA',
                'country_code' => 'SN',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:48',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 193,
                'name' => 'Serbian Dinar',
                'code' => 'RSD',
                'symbol' => 'Дин.',
                'country_code' => 'RS',
                'exchange_rate' => '1.3359',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:48',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 194,
                'name' => 'Seychellois Rupee',
                'code' => 'SCR',
                'symbol' => '₨',
                'country_code' => 'SC',
                'exchange_rate' => '0.1724',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:48',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 195,
                'name' => 'Sierra Leonean Leone',
                'code' => 'SLL',
                'symbol' => 'Le',
                'country_code' => 'SL',
                'exchange_rate' => '227.7878',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:48',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 196,
                'name' => 'Singapore Dollar',
                'code' => 'SGD',
                'symbol' => 'S$',
                'country_code' => 'SG',
                'exchange_rate' => '0.0163',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:49',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 197,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'SK',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:49',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 198,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'SI',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:49',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 199,
                'name' => 'Smaller Territories of the UK',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'XG',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:49',
                'updated_at' => '2022-12-26 14:32:16',
            ]
        ]);

        DB::table('currencies')->insert([
            [
                'id' => 200,
                'name' => 'Solomon Islands Dollar',
                'code' => 'SBD',
                'symbol' => '$',
                'country_code' => 'SB',
                'exchange_rate' => '0.0996',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:49',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 201,
                'name' => 'Somali Shilling',
                'code' => 'SOS',
                'symbol' => 'S',
                'country_code' => 'SO',
                'exchange_rate' => '6.8718',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:49',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 202,
                'name' => 'South African Rand',
                'code' => 'ZAR',
                'symbol' => 'R',
                'country_code' => 'ZA',
                'exchange_rate' => '0.2055',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:49',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 203,
                'name' => 'British Pound Sterling',
                'code' => 'GBP',
                'symbol' => '£',
                'country_code' => 'GS',
                'exchange_rate' => '0.0100',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:50',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 204,
                'name' => 'South Sudan',
                'code' => 'SSP',
                'symbol' => '£',
                'country_code' => 'SS',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:50',
                'updated_at' => '2022-12-26 14:32:16',
            ],
            [
                'id' => 205,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country_code' => 'ES',
                'exchange_rate' => '0.0114',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:50',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 206,
                'name' => 'Sri Lankan Rupee',
                'code' => 'LKR',
                'symbol' => '₨',
                'country_code' => 'LK',
                'exchange_rate' => '4.4156',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:50',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 207,
                'name' => 'Sudanese Pound',
                'code' => 'SDG',
                'symbol' => 'ج.س.',
                'country_code' => 'SD',
                'exchange_rate' => '6.9201',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:50',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 208,
                'name' => 'Surinamese Dollar',
                'code' => 'SRD',
                'symbol' => '$',
                'country_code' => 'SR',
                'exchange_rate' => '0.3824',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:50',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 209,
                'name' => 'Norwegian Krone',
                'code' => 'NOK',
                'symbol' => 'kr',
                'country_code' => 'SJ',
                'exchange_rate' => '0.1191',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:51',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 210,
                'name' => 'Swazi Lilangeni',
                'code' => 'SZL',
                'symbol' => 'E',
                'country_code' => 'SZ',
                'exchange_rate' => '0.2064',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:51',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 211,
                'name' => 'Swedish Krona',
                'code' => 'SEK',
                'symbol' => 'kr',
                'country_code' => 'SE',
                'exchange_rate' => '0.1271',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:51',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 212,
                'name' => 'Swiss Franc',
                'code' => 'CHF',
                'symbol' => 'CHF',
                'country_code' => 'CH',
                'exchange_rate' => '0.0113',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:51',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 213,
                'name' => 'Syrian Pound',
                'code' => 'SYP',
                'symbol' => '£',
                'country_code' => 'SY',
                'exchange_rate' => '30.3701',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:51',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 214,
                'name' => 'New Taiwan Dollar',
                'code' => 'TWD',
                'symbol' => 'NT$',
                'country_code' => 'TW',
                'exchange_rate' => '0.3715',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:51',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 215,
                'name' => 'Tajikistani Somoni',
                'code' => 'TJS',
                'symbol' => 'SM',
                'country_code' => 'TJ',
                'exchange_rate' => '0.1233',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:52',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 216,
                'name' => 'Tanzanian Shilling',
                'code' => 'TZS',
                'symbol' => 'TSh',
                'country_code' => 'TZ',
                'exchange_rate' => '28.1879',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:52',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 217,
                'name' => 'Thai Baht',
                'code' => 'THB',
                'symbol' => '฿',
                'country_code' => 'TH',
                'exchange_rate' => '0.4200',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:52',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 218,
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'symbol' => 'CFA',
                'country_code' => 'TG',
                'exchange_rate' => '7.4663',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:52',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 219,
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => '$',
                'country_code' => 'TK',
                'exchange_rate' => '0.0193',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:52',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 220,
                'name' => 'Tongan Paanga',
                'code' => 'TOP',
                'symbol' => 'T$',
                'country_code' => 'TO',
                'exchange_rate' => '0.0285',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:52',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 221,
                'name' => 'Trinidad and Tobago Dollar',
                'code' => 'TTD',
                'symbol' => 'TT$',
                'country_code' => 'TT',
                'exchange_rate' => '0.0820',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:53',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 222,
                'name' => 'Tunisian Dinar',
                'code' => 'TND',
                'symbol' => 'د.ت',
                'country_code' => 'TN',
                'exchange_rate' => '0.0379',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:53',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 223,
                'name' => 'Turkish Lira',
                'code' => 'TRY',
                'symbol' => '₺',
                'country_code' => 'TR',
                'exchange_rate' => '0.2262',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:53',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 224,
                'name' => 'Turkmenistani Manat',
                'code' => 'TMT',
                'symbol' => 'T',
                'country_code' => 'TM',
                'exchange_rate' => '0.0424',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:53',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 225,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'TC',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:53',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 226,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country_code' => 'TV',
                'exchange_rate' => '0.0180',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:53',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 227,
                'name' => 'Ugandan Shilling',
                'code' => 'UGX',
                'symbol' => 'USh',
                'country_code' => 'UG',
                'exchange_rate' => '43.9848',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:54',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 228,
                'name' => 'Ukrainian Hryvnia',
                'code' => 'UAH',
                'symbol' => '₴',
                'country_code' => 'UA',
                'exchange_rate' => '0.4462',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:54',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 229,
                'name' => 'United Arab Emirates Dirham',
                'code' => 'AED',
                'symbol' => 'د.إ',
                'country_code' => 'AE',
                'exchange_rate' => '0.0444',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:54',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 230,
                'name' => 'British Pound Sterling',
                'code' => 'GBP',
                'symbol' => '£',
                'country_code' => 'GB',
                'exchange_rate' => '0.0100',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:54',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 231,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'US',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:54',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 232,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'UM',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:54',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 233,
                'name' => 'Uruguayan Peso',
                'code' => 'UYU',
                'symbol' => '$U',
                'country_code' => 'UY',
                'exchange_rate' => '0.4635',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:55',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 234,
                'name' => 'Uzbekistan Som',
                'code' => 'UZS',
                'symbol' => 'лв',
                'country_code' => 'UZ',
                'exchange_rate' => '135.4118',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:55',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 235,
                'name' => 'Vanuatu Vatu',
                'code' => 'VUV',
                'symbol' => 'VT',
                'country_code' => 'VU',
                'exchange_rate' => '1.4315',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:55',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 236,
                'name' => 'Vatican City State (Holy See)',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'VA',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:55',
                'updated_at' => '2022-12-26 14:32:16',
            ],
            [
                'id' => 237,
                'name' => 'Venezuelan Bolívar Fuerte',
                'code' => 'VEF',
                'symbol' => 'Bs',
                'country_code' => 'VE',
                'exchange_rate' => '9999.9999',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:55',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 238,
                'name' => 'Vietnamese Dong',
                'code' => 'VND',
                'symbol' => '₫',
                'country_code' => 'VN',
                'exchange_rate' => '285.3240',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:55',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 239,
                'name' => 'Virgin Islands (British)',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'VG',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:55',
                'updated_at' => '2022-12-26 14:32:16',
            ],
            [
                'id' => 240,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country_code' => 'VI',
                'exchange_rate' => '0.0121',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:56',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 241,
                'name' => 'CFP Franc',
                'code' => 'XPF',
                'symbol' => '₣',
                'country_code' => 'WF',
                'exchange_rate' => '1.3641',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:56',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 242,
                'name' => 'Moroccan Dirham',
                'code' => 'MAD',
                'symbol' => 'MAD',
                'country_code' => 'EH',
                'exchange_rate' => '0.1269',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:56',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 243,
                'name' => 'Yemeni Rial',
                'code' => 'YER',
                'symbol' => '﷼',
                'country_code' => 'YE',
                'exchange_rate' => '3.0257',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:56',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 244,
                'name' => 'Yugoslavia',
                'code' => NULL,
                'symbol' => NULL,
                'country_code' => 'YU',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:56',
                'updated_at' => '2022-12-26 14:32:16',
            ],
            [
                'id' => 245,
                'name' => 'Zambian Kwacha',
                'code' => 'ZMW',
                'symbol' => 'ZK',
                'country_code' => 'ZM',
                'exchange_rate' => '0.2164',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:56',
                'updated_at' => '2022-12-26 14:32:18',
            ],
            [
                'id' => 246,
                'name' => 'Zimbabwe',
                'code' => 'ZWD',
                'symbol' => 'Z$',
                'country_code' => 'ZW',
                'exchange_rate' => '0.0000',
                'status' => 1,
                'created_at' => '2022-12-26 14:08:57',
                'updated_at' => '2022-12-26 14:32:16',
            ],
        ]);

        DB::unprepared('SET IDENTITY_INSERT currencies OFF');

        DB::commit();
    }
}
